### ISSUE TITLE
Error returning JSON payload, even if stringified.

### ISSUE THREAD

**Issue by glennblock** [auth0/slash-webtask#1]
I've created a `curl` [task](https://gist.github.com/glennblock/290d84a3741fc5829a28a56863bc9a3e). The way you use it is:

`/wt run curl https://api.github.com/orgs/auth0`

which returns the following:

```text
"{\"login\":\"auth0\",\"id\":2824157,\"url\":\"https://api.github.com/orgs/auth0\",\"repos_url\":\"https://api.github.com/orgs/auth0/repos\",\"events_url\":\"https://api.github.com/orgs/auth0/events\",\"hooks_url\":\"https://api.github.com/orgs/auth0/hooks\",\"issues_url\":\"https://api.github.com/orgs/auth0/issues\",\"members_url\":\"https://api.github.com/orgs/auth0/members{/member}\",\"public_members_url\":\"https://api.github.com/orgs/auth0/public_members{/member}\",\"avatar_url\":\"https://avatars.githubusercontent.com/u/2824157?v=3\",\"description\":\"\",\"name\":\"Auth0\",\"company\":null,\"blog\":\"https://auth0.com\",\"location\":\"Seattle\",\"email\":\"hello@auth0.com\",\"public_repos\":335,\"public_gists\":0,\"followers\":0,\"following\":0,\"html_url\":\"https://github.com/auth0\",\"created_at\":\"2012-11-17T23:55:00Z\",\"updated_at\":\"2016-10-02T11:13:26Z\",\"type\":\"Organization\"}" 
```

Using this command `/wt run curl http://dev.markitondemand.com/MODApis/Api/v2/Quote/json?symbol=GOOG` however fails with this error in slack 

```text
Darn – that slash command didn't work. If you see this message more than once we suggest you contact @tomek>.
```

Though the logs in the editor show that the payload was returned:

```text
8:24:14 AM: finished webtask request 1475609051955.300244 with HTTP 200 in 2828ms
8:24:14 AM: good
{"Status":"SUCCESS","Name":"Alphabet Inc","Symbol":"GOOGL","LastPrice":800.38,"Change":-3.67999999999995,"ChangePercent":-0.457677287764588,"Timestamp":"Mon Oct 3 00:00:00 UTC-04:00 2016","MSDate":42646,"MarketCap":275066594600,"Volume":1489212,"ChangeYTD":778.01,"ChangePercentYTD":2.87528437937816,"High":803.54,"Low":796.23,"Open":802.55}
RUNNER
```

# Notes

* The code is currently stringiying the JSON, though the Github response works without stringification.
* Currently I am just returning the body (which Slack docs support). I tried returning `{"text":"..."}` or using attachments. All worked with the Github call but not with the stock quote call.

**Comment by tjanczuk** [comment]
I can't repro this - both cases work. Aside: your "good" code path calls the callback twice, which may have caused some unintended consequences or race conditions. Anyway, /wt is a different code base than it used to be 17 days ago, so I'd say let's reopen if you see any oddities.
