### ISSUE TITLE
Error "unable to read the named webtask"

### ISSUE THREAD

**Issue by jgelsey** [auth0/slash-webtask#4]
I get the error:
```
Oops! There was a problem running a slash webtask: unable to read the named webtask
Please file issues at https://github.com/auth0/slash-webtask/issues.
```
when trying run either 
`/wt lead mfitzbaxter@atlassian.com` 
or
`/wt tenant atlassian@us`

(or any other lead or tenant I tried)

**Comment by tjanczuk** [comment]
This was point in time, it is fixed now.
