### ISSUE TITLE
/wt show all does not work

### ISSUE THREAD

**Issue by astanciu** [auth0/slash-webtask#5]
`Oops! There was a problem getting code of a slash webtask: unable to read the named webtask`

**Comment by bart-blommaerts** [comment]
Can reproduce.

![image](https://cloud.githubusercontent.com/assets/3988458/19549740/512820dc-96a6-11e6-9f6d-a12b8a4bfa13.png)

**Comment by tjanczuk** [comment]
`/wt show my_webtask` -> only shot it to yourself  
`/wt show my_webtask public` -> show it to everybody in the channel
